### ISSUE TITLE
Change the notion of White/Black with P1/P2 to allow variable naming of colours to starting player

### ISSUE THREAD

**Issue by JamesHeppell** [Mind-Sports-Games/lila#116]
Replace Color with Player class, and White/Black with P1/P2 (or other) to allow variable naming of colours to starting player
Shogi ( P1 - Sente, P2 - Gote)
Xiangqi ( P1 - Red, P2 - Black)
Lines Of Action (P1 - Black, P2 - white) (same as some variants of draughts)

**Comment by msomatt** [comment]
Deployed under https://github.com/Mind-Sports-Games/lila/pull/153
