### ISSUE TITLE
fix playstrategy.org tv 

### ISSUE THREAD

**Issue by DakshCodess** [Mind-Sports-Games/lila#138]
Playstrategy.org tv dosen't show up any games played perviously . Here is the screenshot 
![IMG_20220113_104432](https://user-images.githubusercontent.com/97610126/149270250-825688ac-7610-4d66-bddc-873ba2a9b99a.jpg)
It shows error 404 page not found . fix this

**Comment by msomatt** [comment]
We've done some improvements to the TV page. It now doesnt 404
