### ISSUE TITLE
API usage

### ISSUE THREAD

**Issue by ddugovic** [Mind-Sports-Games/lila#276]
Hey, I'm making a Discord bot to get player ratings, live game URLs etc. similar to https://github.com/ddugovic/lishogi-discord .  How do I use your API?

**Comment by JamesHeppell** [comment]
Hi, thanks for your interest.  We haven't looked into supporting the api yet (out of the box it will probably be the same as lichess, but it's possibly broken in any number of ways). We will take a look at this in the following days/weeks and get back to you.

**Comment by JamesHeppell** [comment]
Hi, we have fixed the api docs and they are now available at https://playstrategy.org/api, let us know if anything doesn't work and we can look into it. The examples are still from lichess, but should yield the same things as from playstrategy.
