### ISSUE TITLE
Takeback button is black instead of grey (only Go games)

### ISSUE THREAD

**Issue by ttBOT-on-Lichess** [Mind-Sports-Games/lila#642]
**Exact URL where the bug happened**
https://playstrategy.org/DgyTOrrtPDXH
**Steps to reproduce the bug**
Go on a go game when it's not your turn
**What did you expect to happen?**
The takeback button is greyed as I've disabled takebacks in the settings 
<img width="675" alt="image" src="https://github.com/Mind-Sports-Games/lila/assets/129761185/9b82333f-4fc1-42f3-88c5-cf46f2bfa206">

**What happened instead?**
The takeback button isn't grey and it seems that if I click on, it'll ask for a takeback. If I click, nothing happen but the takeback button isn't grey. Normally, if i accept takebacks, the button is black. If I don't accept takebacks, the button is grey.
**Operating system and browser version**
Windows 11 ; Microsoft Edge ;  Google Chrome ; Firefox

<img width="711" alt="image" src="https://github.com/Mind-Sports-Games/lila/assets/129761185/9ef87fd6-06e3-4c7e-bc26-71d9e0689eac">
If I ask for a takeback, nothing happen

**Comment by JamesHeppell** [comment]
This looks resolved therefore closing.
