### ISSUE TITLE
Variant page show code

### ISSUE THREAD

**Issue by M-DinhHoangViet** [Mind-Sports-Games/lila#712]
**Exact URL where the bug happened**
https://playstrategy.org/variant
**Steps to reproduce the bug**
https://playstrategy.org/variant
**What did you expect to happen?**
show variant information
**What happened instead?**
show code variant information
**Operating system and browser version**

![image](https://github.com/Mind-Sports-Games/lila/assets/134517889/17ff68aa-66fe-4cc9-b634-4ffcc471a9c6)
![image](https://github.com/Mind-Sports-Games/lila/assets/134517889/02b7b629-6ce1-4d52-b2ce-c285c418b600)

**Comment by M-DinhHoangViet** [comment]
@msomatt @JamesHeppell

**Comment by msomatt** [comment]
Thanks, we fixed a couple of weeks ago
